# Generated by Django 4.1.1 on 2022-09-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=500)),
                ("ativo", models.BooleanField(default=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
