# Generated by Django 4.1.1 on 2022-09-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contato_tarefa_contato_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="contato_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.contato",
            ),
        ),
    ]
